### ISSUE TITLE
Add line numbers

### ISSUE THREAD

**Issue by emipc** [GitbookIO/slate-edit-code#36]
Hi,

Is it possible to add line numbers with this plugin?

Thanks.

**Comment by Soreine** [comment]
At GitBook, we did it using pure CSS. Here is an example: https://codepen.io/elomatreb/pen/hbgxp

If you implement line numbering in the render of your `renderNode` function, you will have issues because Slate is strict on `shouldComponentUpdate` and won't update every lines if just one line changes.
